### ISSUE TITLE
downloading file in unknow format

### ISSUE THREAD

**Issue by rahat22** [mfalaize/cv-generator#3]
When i am clicking on Generate CV button it is downloading file in unknown format not in PDF.

**Comment by mfalaize** [comment]
The aim of this project is to generate website for your CV (you can see a demo [here](http://demo.cvgenerator.maxime-falaize.fr/)) In this website you can actually generate PDF but you cannot generate PDF directly from the cvgenerator app. The Generate CV button will generate the zip file which bundle all the CV website as it is in the demo.

And if you talk about Save CV button instead of Generate CV (because Generate CV button generate a zip file, not unknown format), as far as I remember, it is JSON format but I could not add json suffix with javascript (I would need flash plugin and I did not want to use it in my project).

**Comment by rahat22** [comment]
Thanks.

But when I am clicking on "Generate the CV" button on top it is not downloading or opening file in PDF format as demo showing.

Could you please help me out?

Ray

Sent from my iPhone

On 15 May 2016, at 5:54 PM, Maxime Falaize <notifications@github.com<mailto:notifications@github.com>> wrote:


The aim of this project is to generate website for your CV (you can see a demo here<http://demo.cvgenerator.maxime-falaize.fr/>) In this website you can actually generate PDF but you cannot generate PDF directly from the cvgenerator app. The Generate CV button will generate the zip file which bundle all the CV website as it is in the demo.

And if you talk about Save CV button instead of Generate CV (because Generate CV button generate a zip file, not unknown format), as far as I remember, it is JSON format but I could not add json suffix with javascript (I would need flash plugin and I did not want to use it in my project).

-

**Comment by mfalaize** [comment]
What browser do you use ? I tested with Firefox and Chrome and it works.

Also, it appears you didn't understand the purpose of the Generate CV button. It does not generate the PDF but the website which you can host and serve "as is" (it only contains HTML and Javascript so you don't need server side language such as PHP or Java). An exemple of generated website is available [here](http://demo.cvgenerator.maxime-falaize.fr).
